name: Deploy in beta
on: 
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh 2 commands using password
        uses: appleboy/ssh-action@master
        env:
          CLONE_DIR: "/home/john/node-grpx"
          REPO_URL: ${{ github.repository }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Hello world $CLONE_DIR"
            rm -rf /home/john/front-grp3
            git clone -b develop git@github.com:najat-Filali/group3-front.git /home/john/front-grp3
            npm install
            npm run build
            cp .env.dist ./dist/.env
            cd dist && npm install
            sed -i 's/xenv/prod/g' .env  
            sed -i 's/xdbhost/${{ secrets.PROD_DB_HOST }}/g' .env
            sed -i 's/xdbuser/${{ secrets.PROD_DB_USER }}/g' .env
            sed -i 's/xdbpwd/${{ secrets.PROD_DB_PWD }}/g' .env
            sed -i 's/xdbname/${{ secrets.PROD_DB_DATABASE }}/g' .env
            pm2 stop app-grpx > /dev/null 2>&1
            pm2 start index.js --name app-grpx



