name: Deploy in beta
on: 
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh 2 commands using password
        uses: appleboy/ssh-action@master
        env:
          CLONE_DIR: "/home/john/front-grp3"
          REPO_URL: ${{ github.repository }}
          #EXPRESS_PORT: ${{ secrets.EXPRESS_PORT }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: CLONE_DIR,REPO_URL
          script: |
            echo "Hello world"
            rm -rf $CLONE_DIR
            git clone -b develop git@github.com:$REPO_URL.git $CLONE_DIR
            cd $CLONE_DIR
            ls -la
            