name: Deploy in beta
on: 
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh 2 commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Hello world $CLONE_DIR"
            rm -rf /home/john/front-grp3
            git clone -b develop git@github.com:najat-Filali/group3-front.git /home/john/front-grp3
            npm install
            npm run build
            